export const GET_GLOBAL_POSTS = 'GET_GLOBAL_POSTS'
export const GET_ONE_POST = 'GET_ONE_POST'

export const FOLLOW_CHOSEN_USER = 'FOLLOW_CHOSEN_USER'
export const FAVORITE_CHOSEN_ARTICLE = 'FAVORITE_CHOSEN_ARTICLE'