    export const CLICK_SIGN_UP = 'CLICK_SIGN_UP'
    export const INPUT_VALUE_REGISTER_USERNAME = 'INPUT_VALUE_REGISTER_USERNAME'
    export const INPUT_VALUE_REGISTER_EMAIL = 'INPUT_VALUE_REGISTER_EMAIL'
    export const INPUT_VALUE_REGISTER_PASS = 'INPUT_VALUE_REGISTER_PASS'