
export const IS_LOG_IN = 'IS_LOG_IN'
export const IS_LOG_OUT = 'IS_LOG_OUT'
export const GET_USER_ON_TOKEN = 'GET_USER_ON_TOKEN'
export const GET_ERROR_ON_TOKEN = 'GET_ERROR_ON_TOKEN'
export const LOADING_LS = 'LOADING_LS'
export const GET_ERROR_ON_UPDATE_INFO = 'GET_ERROR_ON_UPDATE_INFO'
export const UPDATE_INFO = 'UPDATE_INFO'
export const CLICK_TO_HEADER_LINK = 'CLICK_TO_HEADER_LINK'

